// Generated by Wrangler by running `wrangler types src/types/env.d.ts`

interface Env {
	JSON_DATA: KVNamespace;
	ENVIRONMENT: "production" | "development" | "staging";
	GITHUB_TOKEN: string;
	OPENAI_API_KEY: string;
	AI: Ai;
}
