// Generated by Wrangler by running `wrangler types src/types/env.d.ts`

export interface Env {
	API_KEY: string;
	ENVIRONMENT: "production" | "development" | "staging";
	OPENAI_API_KEY: string;
	AI: Ai;
}
